baseURL = 'https://example.org/'
languageCode = 'en'
title = 'Zuhaib Ul Zamann'
theme = 'coder'
defaultContentLanguage = 'en'
enableEmoji = true

[pagination]
pagerSize = 6


[markup]
[markup.highlight]
noClasses = false
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Zuhaib Ul Zamann"
description = "Zuhaib Ul Zamann's portfolio website"
keywords = "blog,developer,personal"
info = ["Software Development Engineer", "Sprinklr"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"

colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/zuhaib786/"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/zuhaibulzaman.786/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/ZuhaibUlZaman1/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/zuhaib-ul-zamann-0520a5190//"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://medium.com/@zuhaibulzaman.786"



[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"




[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Résumé"
weight = 5
url = "resume/"

[[languages.en.menu.main]]
name = "Study"
url = "study/"
weight = 6

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'
